spring.application.name=tdms
spring.datasource.url=jdbc:mysql://localhost:3307/tdms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=tdms_user
spring.datasource.password=tdms123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

tdms.storage.root=./tdms-data
tdms.storage.create-if-missing=true

server.error.include-message=always

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=fhcampus.nilspetsch.tdms.api
